export const CART_PICK_STATUS = {PROCESSED: "PROCESSED", UNPROCESSED: "UNPROCESSED"} as const;

export const CART_ALLOCATION_STATUS = {
    UNFULFILLED: "UNFULFILLED",
    FULFILLED: "FULFILLED",
    NULL: "null",
    PARTIAL: "PARTIAL"
} as const;

export const CART_REQUEST_TYPE = {
    STANDARD: "STANDARD",
    AFTER_HOUR: "AFTER_HOUR",
    ALLOCATION: "ALLOCATION",
    PICK: "PICK",
    DELETE: "DELETE",
    INITIAL_ALLOCATION: "INITIAL_ALLOCATION"
} as const;
