export const EXTERNAL_FACILITY_ID = {
    GAGD: "GAGD",
    GACH: "GACH",
    GAHJ: "GAHJ"
} as const;

export const FACILITY_SUPPLY_DAYS = {
    SEVEN_DAYS: 7,
    THIRTY_DAYS: 30
};

export const FACILITY_NOTIFICATION_TYPES = {
    FACILITY_CHECKLIST_INCOMPLETE: "FACILITY_CHECKLIST_INCOMPLETE"
};
