export const FACILITY_CHECKLIST_PRIORITY = {
    ISSUE_REPORT: 0,
    MEDICATION: 1,
    MENTAL_HEALTH: 2,
    EMPLOYEE_SAFETY: 3,
    ENVIRONMENTAL: 4,
    EQUIPMENT_MALFUNCTION: 5
} as const;

export const FACILITY_CHECKLIST_EVENTS = {
    MEDICATION: "MEDICATION",
    MENTAL_HEALTH: "MENTAL_HEALTH",
    EMPLOYEE_SAFETY: "EMPLOYEE_SAFETY",
    ENVIRONMENTAL: "ENVIRONMENTAL",
    EQUIPMENT_MALFUNCTION: "EQUIPMENT_MALFUNCTION",
    ISSUE_REPORT: "ISSUE_REPORT"
} as const;
