export const FILE_EXTENSIONS = {CSV: "csv", AC: "AC1", JPEG: "jpeg", PNG: "png", TXT: "txt"} as const;

export const FILE_ENCODINGS = {BASE64: "base64", ASCII: "ascii", UTF8: "utf-8"} as const;

export const FILE_STATUSES = {
    RECEIVED: "RECEIVED",
    QUEUED: "QUEUED",
    PROCESSED: "PROCESSED",
    PARTIAL: "PARTIAL",
    FAILED: "FAILED"
};

export const ADMIN_FILE_PROCESSES = {
    BULK_UPSERT_ADMINS: "BULK_UPSERT_ADMINS"
} as const;

export const FORMULARY_FILE_PROCESSES = {
    BULK_ADD_FORMULARY: "BULK_ADD_FORMULARY",
    BULK_REMOVE_FORMULARY: "BULK_REMOVE_FORMULARY"
} as const;

export const INVENTORY_FILE_PROCESSES = {
    NON_CONTROLLED_ADD: "BULK_ADD_NON_CONTROLLED_INVENTORY_ADD",
    NON_CONTROLLED_EDIT_DELETE: "BULK_ADD_NON_CONTROLLED_INVENTORY_EDIT_DELETE",
    CONTROLLED_ADD: "BULK_ADD_CONTROLLED_INVENTORY_ADD",
    CONTROLLED_EDIT_DELETE: "BULK_ADD_CONTROLLED_INVENTORY_ADD_EDIT_DELETE"
} as const;

export const FORMULARY_LEVEL_FILE_PROCESSES = {
    BULK_ADD_FORMULARY_LEVELS: "BULK_ADD_FORMULARY_LEVELS"
} as const;

export const SERVICE_DISRUPTION_FILE_PROCESSES = {BULK_ADD_SERVICE_DISRUPTION: "BULK_ADD_SERVICE_DISRUPTION"} as const;

export const SHERIFF_DIVISION_FILE_PROCESSES = {
    BULK_ADD_JAIL_DIVISION: "BULK_ADD_JAIL_DIVISION",
    BULK_ADD_SUPPORT_DIVISION: "BULK_ADD_SUPPORT_DIVISION",
    BULK_ADD_FIELD_DIVISION: "BULK_ADD_FIELD_DIVISION",
    BULK_ADD_COURT_DIVISION: "BULK_ADD_COURT_DIVISION"
};

export const ADMINISTRATIVE_DIVISION_FILE_PROCESSES = {
    BULK_ADD_ADMINISTRATIVE_DIVISION: "BULK_ADD_ADMINISTRATIVE_DIVISION",
    BULK_ADD_SWORN_PERSONNEL_DIVISION: "BULK_ADD_SWORN_PERSONNEL_DIVISION"
};

export const CONTACT_FILE_PROCESSES = {
    BULK_ADD_CONTACTS: "BULK_ADD_CONTACTS",
    BULK_REMOVE_CONTACTS: "BULK_REMOVE_CONTACTS"
} as const;

export const EXTERNAL_FILE_PROCESSES = {
    SFTP_FILE_PROCESS: "SFTP_FILE_PROCESS"
} as const;

export const FACILITY_LOCATION_PROCESSES = {
    BULK_ADD_FACILITY_LOCATION: "BULK_ADD_FACILITY_LOCATION"
} as const;

export const REFERENCE_GUIDE_PROCESSES = {
    BULK_ADD_REFERENCE_GUIDE: "BULK_ADD_REFERENCE_GUIDE"
} as const;

export const CART_REQUEST_PROCESSES = {
    INITIAL_ALLOCATION: "BULK_ADD_INITIAL_ALLOCATION"
} as const;

export const FORMULARY_LEVELS_PROCESSES = {
    BULK_ADD_FORMULARY_LEVELS: "BULK_ADD_FORMULARY_LEVELS"
} as const;

export const REPOSITORIES = {
    ADMIN: "ADMIN",
    SAFE_REPORT: "SAFE_REPORT",
    SAFE_ASSIGNMENT_COMMENT: "SAFE_ASSIGNMENT_COMMENT",
    FORMULARY: "FORMULARY",
    INVENTORY: "INVENTORY",
    SERVICE_DISRUPTION: "SERVICE_DISRUPTION",
    SHERIFF_DIVISION: "SHERIFF_DIVISION",
    CONTACTS: "CONTACTS",
    SFTP: "SFTP",
    FACILITY_LOCATION: "FACILITY_LOCATION",
    ADMINISTRATIVE_DIVISION: "ADMINISTRATIVE_DIVISION",
    INVENTORY_CONTROL: "INVENTORY_CONTROL",
    REFERENCE_GUIDE: "REFERENCE_GUIDE",
    CART_REQUEST_LOG: "CART_REQUEST_LOG",
    FACILITY: "FACILITY",
    FACILITY_CHECKLIST: "FACILITY_CHECKLIST",
    FORMULARY_LEVELS: "FORMULARY_LEVELS",
    INVENTORY_HISTORY: "INVENTORY_HISTORY",
    CONTROLLED_DRUG: "CONTROLLED_DRUG",
    SHIFT_COUNT_LOG: "SHIFT_COUNT_LOG"
} as const;

export const REPOSITORY_PROCESSES = {
    ADMIN: Object.values(ADMIN_FILE_PROCESSES),
    FORMULARY: Object.values(FORMULARY_FILE_PROCESSES),
    INVENTORY: Object.values(INVENTORY_FILE_PROCESSES),
    SERVICE_DISRUPTION: Object.values(SERVICE_DISRUPTION_FILE_PROCESSES),
    CONTACTS: Object.values(CONTACT_FILE_PROCESSES),
    SFTP: Object.values(EXTERNAL_FILE_PROCESSES),
    FACILITY_LOCATION: Object.values(FACILITY_LOCATION_PROCESSES),
    REFERENCE_GUIDE: Object.values(REFERENCE_GUIDE_PROCESSES),
    CART_REQUEST_LOG: Object.values(CART_REQUEST_PROCESSES),
    INITIAL_ALLOCATION: Object.values(CART_REQUEST_PROCESSES),
    FORMULARY_LEVELS: Object.values(FORMULARY_LEVELS_PROCESSES)
};

export const ROW_ACTION = {
    ADD: "add",
    EDIT: "edit",
    DELETE: "delete",
    REPLEN: "replen"
} as const;

export const FACILITY_FREE_REPOSITORIES = [
    REPOSITORIES.ADMIN,
    REPOSITORIES.FORMULARY,
    REPOSITORIES.SHERIFF_DIVISION,
    REPOSITORIES.ADMINISTRATIVE_DIVISION
];
