export const MEDPASS_RESULT = {
    ADMINISTERED: "Administered"
};

export const CONTROLLED_TYPE = {PATIENT_SPECIFIC: "PATIENT_SPECIFIC", STOCK: "STOCK"} as const;

export const INVENTORY_NOTIFICATION_TYPES = {
    INVENTORY_DEPLETE: "INVENTORY_DEPLETE"
};
