export const MAX_ROW_NUMBER = 9999;

export const PERPETUAL_INVENTORY_FOLDERS = {
    PERPETUAL_INVENTORY: "PERPETUAL_INVENTORY",
    PERPETUAL_INVENTORY_DEDUCTION: "PERPETUAL_INVENTORY_DEDUCTION"
};

export const PERPETUAL_SIGNATURE_TYPES = {
    STAFF_SIGNATURE: "STAFF_SIGNATURE",
    ADMIN_SIGNATURE: "ADMIN_SIGNATURE",
    WITNESS_SIGNATURE: "WITNESS_SIGNATURE"
};
