export const PERPETUAL_INVENTORY_DEDUCTION_TYPES = {
    DOSE_ADMINISTERED: "DOSE_ADMINISTERED",
    WASTED: "WASTED",
    DESTROYED: "DESTROYED",
    TRANSFERRED: "TRANSFERRED",
    RETURNED_TO_PATIENT: "RETURNED_TO_PATIENT",
    RETURNED_TO_PROPERTY: "RETURNED_TO_PROPERTY"
};
