export const SAFE_REPORT_NOTIFICATION_TYPES = {
    ASSIGN: "ASSIGN",
    OWNERSHIP_TRANSFER: "OWNERSHIP_TRANSFER",
    RETURNED_OWNER: "RETURNED_OWNER",
    RETURNED_SENDER: "RETURNED_SENDER",
    IN_REVIEW: "IN_REVIEW",
    CLOSED: "CLOSED",
    SUBMITTED: "SUBMITTED",
    AWARENESS: "AWARENESS"
};
