export const SHIFT_COUNT_FOLDERS = {
    SHIFT_COUNT: "SHIFT_COUNT"
};

export const SHIFT_COUNT_TYPES = {
    HAND_OFF_SIGNATURE: "HAND_OFF_SIGNATURE",
    RECEIVER_SIGNATURE: "RECEIVER_SIGNATURE"
};

export const SHIFT_COUNT_NOTIFICATION_TYPE = {
    DISCREPANCY: "SHIFT_COUNT_DISCREPANCY"
};
