export const AppErrorMessage = {
    GET_FILES: "::GET_FILES",
    BULK_UPSERT_ADMINS: {
        PROCESS: "BULK_UPSERT_ADMINS",
        UPSERT_ADMIN: "::UPSERT_ADMIN"
    },
    BULK_ADD_FORMULARY: {
        PROCESS: "BULK_ADD_FORMULARY",
        ADD_FORMULARY: "::ADD_FORMULARY"
    },
    BULK_ADD_INVENTORY: {
        PROCESS: "BULK_ADD_INVENTORY",
        ADD_INVENTORY: "::ADD_INVENTORY",
        ADD_FORMULARY_LEVELS: "::ADD_FORMULARY_LEVELS"
    },
    BULK_ADD_FORMULARY_LEVEL: {
        PROCESS: "BULK_ADD_FORMULARY_LEVEL",
        ADD_FORMULARY_LEVELS: "::ADD_FORMULARY_LEVELS"
    },
    SAPPHIRE_MED_PASS: {
        PROCESS: "SAPPHIRE_MED_PASS",
        FETCH_INVENTORY: "::FETCH_INVENTORY",
        PROCESS_QUANTITY: "::PROCESS_QUANTITY",
        LOT_QUANTITY: "::LOT_QUANTITY"
    },
    HISTORY_PHYSICAL: {
        PROCESS: "HISTORY_PHYSICAL",
        FETCH_DATA: "::FETCH_DATA",
        PROCESS_DATA: "::PROCESS_DATA",
        DATA_POPULATION_FAILED: "::DATA_POPULATION_FAILED",
        LINK_PATIENT: "::LINK_PATIENT_FAILED"
    },
    BULK_ADD_SERVICE_DISRUPTION: {
        PROCESS: "BULK_ADD_SERVICE_DISRUPTION",
        FILE_FAILED: "::FILE_FAILED",
        SERVICE_DISRUPTION_FAILED: "::SERVICE_DISRUPTION_FAILED"
    },
    REMOVE_BUCKET_PROCESSED_FILES: {
        PROCESS: "REMOVE_BUCKET_PROCESSED_FILES",
        DELETE_FAILED: "::DELETE_FAILED"
    },
    BULK_ADD_CONTACTS: {
        PROCESS: "BULK_ADD_CONTACTS",
        ADD_CONTACTS: "::ADD_CONTACTS"
    },
    BULK_ADD_DIVISION: {
        PROCESS: "BULK_ADD_DIVISIONS"
    },
    BULK_ADD_PATIENTS: {
        PROCESS: "BULK_ADD_PATIENTS",
        ADD_PATIENTS: "::ADD_PATIENTS"
    },
    ADD_MEDICATION_LIST: {
        PROCESS: "ADD_MEDICATION_LIST",
        ADD_MEDICATION: "::ADD_MEDICATION"
    },
    REMOVE_CLOUD_STORAGE_FILES: {
        PROCESS: "REMOVE_CLOUD_STORAGE_FILES",
        DELETE_FAILED: "::DELETE_FAILED"
    },
    BULK_ADD_LOCATIONS: {
        PROCESS: "BULK_ADD_LOCATIONS"
    },
    BULK_ADD_ADMINISTRATIVE_DIVISION: {
        PROCESS: "BULK_ADD_ADMINISTRATIVE_DIVISION"
    },
    BULK_DEDUCT_INVENTORY_WHEN_EXPIRED_OR_DEPLETED: {
        PROCESS: "BULK_DEDUCT_INVENTORY_WHEN_EXPIRED_OR_DEPLETED"
    },
    BULK_ADD_REFERENCE_GUIDE_DRUGS: {
        PROCESS: "BULK_ADD_REFERENCE_GUIDE_DRUGS",
        ADD_DRUGS: "::ADD_DRUGS"
    },
    INITIAL_ALLOCATION: {
        PROCESS: "INITIAL_ALLOCATION",
        ALLOCATE: "::ALLOCATE"
    },
    DEACTIVATE_EXPIRED_INVENTORY: {
        PROCESS: "DEACTIVATE_EXPIRED_INVENTORY",
        DEACTIVATE_EXPIRED_INVENTORY: "::DEACTIVATE_EXPIRED_INVENTORY"
    },
    UPLOAD_INVENTORY_HISTORY: {
        PROCESS: "UPLOAD_INVENTORY_HISTORY",
        UPLOAD_INVENTORY: "::UPLOAD_INVENTORY",
        FETCH_INVENTORY: "::FETCH_INVENTORY"
    }
};
