import {container} from "tsyringe";

import {CentralSupplyLogService} from "@application/CentralSupplyLog/CentralSupplyLogService";
import {CentralSupplyLogDrugService} from "@application/CentralSupplyLogDrug/CentralSupplyLogDrugService";
import {FormularyService} from "@application/Formulary/FormularyService";
import {FormularyLevelService} from "@application/FormularyLevel/FormularyLevelService";
import {InventoryService} from "@application/Inventory/InventoryService";

import {AdminRepository} from "@repositories/AdminRepository";
import {AdminRoleRepository} from "@repositories/AdminRoleRepository";
import {AuditLogRepository} from "@repositories/AuditLogRepository";
import {BridgeTherapyLogRepository} from "@repositories/BridgeTherapyLogRepository";
import {CartInventoryLogsRepository} from "@repositories/CartInventoryLogsRepository";
import {CartInventoryLogsDrugRepository} from "@repositories/CartInvetoryLogsDrugRepository";
import {CartRepository} from "@repositories/CartRepository";
import {CartRequestDeductionRepository} from "@repositories/CartRequestDeductionRepository";
import {CartRequestDrugRepository} from "@repositories/CartRequestDrugRepository";
import {CartRequestFormRepository} from "@repositories/CartRequestFormRepository";
import {CartRequestLogRepository} from "@repositories/CartRequestLogRepository";
import {CentralSupplyLogDrugRepository} from "@repositories/CentralSupplyLogDrugRepository";
import {CentralSupplyLogRepository} from "@repositories/CentralSupplyLogRepository";
import {ContactRepository} from "@repositories/ContactRepository";
import {ControlledDrugRepository} from "@repositories/ControlledDrugRepository";
import {DiscrepancyLogRepository} from "@repositories/DiscrepancyLogRepository";
import {DivisionRepository} from "@repositories/DivisionRepository";
import {DivisionSwornRepository} from "@repositories/DivisionSwornRepository";
import {FacilityAdminRepository} from "@repositories/FacilityAdminRepository";
import {FacilityChecklistRepository} from "@repositories/FacilityChecklistRepository";
import {FacilityContactRepository} from "@repositories/FacilityContactRepository";
import {FacilityRepository} from "@repositories/FacilityRepository";
import {FacilityUnitRepository} from "@repositories/FacilityUnitRepository";
import {FileRepository} from "@repositories/FileRepository";
import {FormularyLevelRepository} from "@repositories/FormularyLevelRepository";
import {FormularyRepository} from "@repositories/FormularyRepository";
import {HistoryPhysicalRepository} from "@repositories/HistoryPhysicalRepository";
import {InventoryControlRepository} from "@repositories/InventoryControlRepository";
import {InventoryHistoryRepository} from "@repositories/InventoryHistoryRepository";
import {InventoryRepository} from "@repositories/InventoryRepository";
import LogRepository from "@repositories/LogRepository";
import {MedicationListRepository} from "@repositories/MedicationListRepository";
import {NotificationAdminRepository} from "@repositories/NotificationAdminRepository";
import {NotificationRepository} from "@repositories/NotificationRepository";
import {PatientRepository} from "@repositories/PatientRepository";
import {PerpetualInventoryDeductionRepository} from "@repositories/PerpetualInventoryDeductionRepository";
import {PerpetualInventoryRepository} from "@repositories/PerpetualInventoryRepository";
import {ProcessContactRepository} from "@repositories/ProcessContactRepository";
import {ProcessRepository} from "@repositories/ProcessRepository";
import {ReferenceGuideDrugRepository} from "@repositories/ReferenceGuideDrugRepository";
import {ReferenceGuideRepository} from "@repositories/ReferenceGuideRepository";
import {ReportRepository} from "@repositories/ReportRepository";
import {RoleRepository} from "@repositories/RoleRepository";
import {RoleServiceListRepository} from "@repositories/RoleServiceListRepository";
import {SafeAssignmentCommentRepository} from "@repositories/SafeAssignmentCommentRepository";
import {SafeEventLocationRepository} from "@repositories/SafeEventLocationRepository";
import {SafeFacilityChecklistRepository} from "@repositories/SafeFacilityChecklistRepository";
import {SafeReportEventLocationRepository} from "@repositories/SafeReportEventLocationRepository";
import {SafeReportNotificationRepository} from "@repositories/SafeReportNotificationRepository";
import {SafeReportRepository} from "@repositories/SafeReportRepository";
import {ServiceDependencyRepository} from "@repositories/ServiceDependencyRepository";
import {ServiceDisruptionPatientRepository} from "@repositories/ServiceDisruptionPatientRepository";
import {ServiceDisruptionRepository} from "@repositories/ServiceDisruptionRepository";
import {ServiceListRepository} from "@repositories/ServiceListRepository";
import {RelationBuilder} from "@repositories/Services/RelationBuilder";
import {ShiftCountLogDrugRepository} from "@repositories/ShiftCountLogDrugRepository";
import {ShiftCountLogRepository} from "@repositories/ShiftCountLogRepository";
import {UserSettingRepository} from "@repositories/UserSettingRepository";

import {CloudStorageClient} from "@infraServices/ThirdPartyClient/CloudStorage/CloudStorageClient";
import {EmailClient} from "@infraServices/ThirdPartyClient/Email/EmailClient";
import {SlackClient} from "@infraServices/ThirdPartyClient/Slack/SlackClient";

container.register("IAdminRepository", {useClass: AdminRepository});
container.register("ILogRepository", {useClass: LogRepository});
container.register("IFileRepository", {useClass: FileRepository});
container.register("IFormularyRepository", {useClass: FormularyRepository});
container.register("IInventoryRepository", {useClass: InventoryRepository});
container.register("IServiceDisruptionRepository", {useClass: ServiceDisruptionRepository});
container.register("IServiceDisruptionPatientRepository", {useClass: ServiceDisruptionPatientRepository});
container.register("IFacilityRepository", {useClass: FacilityRepository});
container.register("IContactRepository", {useClass: ContactRepository});
container.register("IFacilityAdminRepository", {useClass: FacilityAdminRepository});
container.register("IUserSettingRepository", {useClass: UserSettingRepository});
container.register("IHistoryPhysicalRepository", {useClass: HistoryPhysicalRepository});
container.register("IDivisionRepository", {useClass: DivisionRepository});
container.register("IDivisionSwornRepository", {useClass: DivisionSwornRepository});
container.register("IPatientRepository", {useClass: PatientRepository});
container.register("IMedicationListRepository", {useClass: MedicationListRepository});
container.register("IFacilityUnitRepository", {useClass: FacilityUnitRepository});
container.register("IBridgeTherapyLogRepository", {useClass: BridgeTherapyLogRepository});
container.register("IRoleRepository", {useClass: RoleRepository});
container.register("IServiceListRepository", {useClass: ServiceListRepository});
container.register("IServiceDependencyRepository", {useClass: ServiceDependencyRepository});
container.register("IRoleServiceListRepository", {useClass: RoleServiceListRepository});
container.register("IAdminRoleRepository", {useClass: AdminRoleRepository});
container.register("IAuditLogRepository", {useClass: AuditLogRepository});
container.register("IRelationBuilder", {useClass: RelationBuilder});
container.register("IInventoryControlRepository", {useClass: InventoryControlRepository});
container.register("IFormularyLevelRepository", {useClass: FormularyLevelRepository});
container.register("ICartRepository", {useClass: CartRepository});
container.register("IFacilityContactRepository", {useClass: FacilityContactRepository});
container.register("IProcessRepository", {useClass: ProcessRepository});
container.register("IProcessContactRepository", {useClass: ProcessContactRepository});
container.register("IFacilityChecklistRepository", {useClass: FacilityChecklistRepository});
container.register("IReferenceGuideRepository", {useClass: ReferenceGuideRepository});
container.register("IReferenceGuideDrugRepository", {useClass: ReferenceGuideDrugRepository});
container.register("IReportRepository", {useClass: ReportRepository});
container.register("ISafeReportRepository", {useClass: SafeReportRepository});
container.register("ISafeEventLocationRepository", {useClass: SafeEventLocationRepository});
container.register("ISafeReportEventLocationRepository", {useClass: SafeReportEventLocationRepository});
container.register("ISafeAssignmentCommentRepository", {useClass: SafeAssignmentCommentRepository});
container.register("ISafeFacilityChecklistRepository", {useClass: SafeFacilityChecklistRepository});
container.register("IProcessRepository", {useClass: ProcessRepository});
container.register("IProcessContactRepository", {useClass: ProcessContactRepository});
container.register("IFacilityContactRepository", {useClass: FacilityContactRepository});
container.register("ICartRepository", {useClass: CartRepository});
container.register("IFacilityChecklistRepository", {useClass: FacilityChecklistRepository});
container.register("ISafeReportNotificationRepository", {useClass: SafeReportNotificationRepository});
container.register("ICartRequestFormRepository", {useClass: CartRequestFormRepository});
container.register("ICartRequestLogRepository", {useClass: CartRequestLogRepository});
container.register("ICartRequestDrugRepository", {useClass: CartRequestDrugRepository});
container.register("ICartRequestDeductionRepository", {useClass: CartRequestDeductionRepository});
container.register("IControlledDrugRepository", {useClass: ControlledDrugRepository});
container.register("INotificationRepository", {useClass: NotificationRepository});
container.register("INotificationAdminRepository", {useClass: NotificationAdminRepository});
container.register("ICentralSupplyLogRepository", {useClass: CentralSupplyLogRepository});
container.register("ICentralSupplyLogDrugRepository", {useClass: CentralSupplyLogDrugRepository});
container.register("IPerpetualInventoryRepository", {useClass: PerpetualInventoryRepository});
container.register("IPerpetualInventoryDeductionRepository", {useClass: PerpetualInventoryDeductionRepository});
container.register("IInventoryHistoryRepository", {useClass: InventoryHistoryRepository});
container.register("ICartInventoryLogsRepository", {useClass: CartInventoryLogsRepository});

container.register("ICartInventoryLogsDrugRepository", {useClass: CartInventoryLogsDrugRepository});
container.register("IDiscrepancyLogRepository", {useClass: DiscrepancyLogRepository});
container.register("IShiftCountLogsRepository", {useClass: ShiftCountLogRepository});
container.register("IShiftCountLogDrugsRepository", {useClass: ShiftCountLogDrugRepository});

container.register("IEmailClient", {useClass: EmailClient});
container.register("ISlackClient", {useClass: SlackClient});
container.register("ICloudStorageClient", {useClass: CloudStorageClient});

container.register("IFormularyService", {useClass: FormularyService});
container.register("IFormularyLevelService", {useClass: FormularyLevelService});
container.register("IInventoryService", {useClass: InventoryService});
container.register("ICentralSupplyLogService", {useClass: CentralSupplyLogService});
container.register("ICentralSupplyLogDrugService", {useClass: CentralSupplyLogDrugService});

export default container;
