import {container} from "tsyringe";

import {CloudStorageUtils} from "@appUtils/CloudStorage/CloudStorageUtils";
import {EmailUtils} from "@appUtils/Email/EmailUtils";
import {SlackUtils} from "@appUtils/Slack/SlackUtils";

import {AdminProcessorService} from "@application/Admin/AdminProcessorService";
import {AdminService} from "@application/Admin/AdminService";
import AdminUserService from "@application/Admin/AdminUserService";
import {AdminRoleService} from "@application/AdminRole/AdminRoleService";
import {AuditLogService} from "@application/AuditLog/AuditLogService";
import AuthService from "@application/Auth/AuthService";
import AuthUserService from "@application/Auth/AuthUserService";
import {BridgeTherapyService} from "@application/BridgeTherapy/BridgeTherapyService";
import {CartService} from "@application/Cart/CartService";
import {CartInventoryService} from "@application/CartInventory/CartInventoryService";
import {CartInventoryLogsService} from "@application/CartInventoryLogs/CartInventoryLogsService";
import {CartInventoryLogsDrugService} from "@application/CartInventoryLogsDrug/CartInventoryLogsDrugService";
import {CartRequestDeductionService} from "@application/CartRequestDeduction/CartRequestDeductionService";
import {CartRequestDrugProcessorService} from "@application/CartRequestDrug/CartRequestDrugProcessorService";
import {CartRequestDrugService} from "@application/CartRequestDrug/CartRequestDrugService";
import {CartRequestFormService} from "@application/CartRequestForm/CartRequestFormService";
import {CartRequestLogService} from "@application/CartRequestLog/CartRequestLogService";
import {CentralSupplyLogService} from "@application/CentralSupplyLog/CentralSupplyLogService";
import {CentralSupplyLogDrugService} from "@application/CentralSupplyLogDrug/CentralSupplyLogDrugService";
import {ContactService} from "@application/Contact/ContactService";
import {ControlledDrugService} from "@application/ControlledDrug/ControlledDrugService";
import {DiscrepancyLogService} from "@application/DiscrepancyLog/DiscrepancyLogService";
import {DivisionService} from "@application/Division/DivisionService";
import {DivisionSwornService} from "@application/DivisionSworn/DivisionSwornService";
import {FacilityService} from "@application/Facility/FacilityService";
import {FacilityAdminService} from "@application/FacilityAdmin/FacilityAdminService";
import {FacilityChecklistService} from "@application/FacilityChecklist/FacilityChecklistService";
import {FacilityContactService} from "@application/FacilityContact/FacilityContactService";
import {FacilityUnitProcessorService} from "@application/FacilityUnit/FacilityUnitProcessorService";
import {FacilityUnitService} from "@application/FacilityUnit/FacilityUnitService";
import {FileProcessorService} from "@application/File/FileProcessorService";
import {FileService} from "@application/File/FileService";
import {FormularyProcessorService} from "@application/Formulary/FormularyProcessorService";
import {FormularyService} from "@application/Formulary/FormularyService";
import {FormularyLevelService} from "@application/FormularyLevel/FormularyLevelService";
import {FormularyLevelsProcessorService} from "@application/FormularyLevel/FormularyLevelsProcessorService";
import {HistoryPhysicalService} from "@application/HistoryPhysical/HistoryPhysicalService";
import {InventoryProcessorService} from "@application/Inventory/InventoryProcessorService";
import {InventoryService} from "@application/Inventory/InventoryService";
import {InventoryControlService} from "@application/InventoryControl/InventoryControlService";
import {InventoryHistoryProcessorService} from "@application/InventoryHistory/InventoryHistoryProcessorService";
import {InventoryHistoryService} from "@application/InventoryHistory/InventoryHistoryService";
import LogService from "@application/Log/LogService";
import {MedicationListService} from "@application/MedicationList/MedicationListService";
import {NotificationService} from "@application/Notification/NotificationService";
import {NotificationAdminService} from "@application/NotificationAdmins/NotificationAdminService";
import {PatientService} from "@application/Patient/PatientService";
import {PerpetualInventoryService} from "@application/PerpetualInventory/PerpetualInventoryService";
import {PerpetualInventoryDeductionService} from "@application/PerpetualInventoryDeduction/PerpetualInventoryDeductionService";
import {ProcessService} from "@application/Process/ProcessService";
import {ProcessContactService} from "@application/ProcessContact/ProcessContactService";
import {ReferenceGuideService} from "@application/ReferenceGuide/ReferenceGuideService";
import {ReferenceGuideDrugProcessorService} from "@application/ReferenceGuideDrug/ReferenceGuideDrugProcessorService";
import {ReferenceGuideDrugService} from "@application/ReferenceGuideDrug/ReferenceGuideDrugService";
import {RefillStockService} from "@application/RefillStock/RefillStockService";
import {ReportService} from "@application/Report/ReportService";
import {RoleService} from "@application/Role/RoleService";
import {RoleServiceListService} from "@application/RoleServiceList/RoleServiceListService";
import {SafeAssignmentCommentService} from "@application/SafeAssignmentComment/SafeAssignmentCommentService";
import {SafeEventLocationService} from "@application/SafeEventLocation/SafeEventLocationService";
import {SafeFacilityChecklistService} from "@application/SafeFacilityChecklist/SafeFacilityChecklistService";
import {SafeReportService} from "@application/SafeReport/SafeReportService";
import {SafeReportEventLocationService} from "@application/SafeReportEventLocation/SafeReportEventLocationService";
import {SafeReportNotificationService} from "@application/SafeReportNotification/SafeReportNotificationService";
import {SamlService} from "@application/Saml/SamlService";
import {ServiceDependencyService} from "@application/ServiceDependency/ServiceDependencyService";
import {ServiceDisruptionProcessorService} from "@application/ServiceDisruption/ServiceDisruptionProcessorService";
import {ServiceDisruptionService} from "@application/ServiceDisruption/ServiceDisruptionService";
import {ServiceDisruptionPatientService} from "@application/ServiceDisruptionPatient/ServiceDisruptionPatientService";
import {ServiceListService} from "@application/ServiceList/ServiceListService";
import {ShiftCountService} from "@application/ShiftCount/ShiftCountService";
import {ShiftCountLogDrugsService} from "@application/ShiftCountLogDrugs/ShiftCountLogDrugsService";
import {ShiftCountLogsService} from "@application/ShiftCountLogs/ShiftCountLogsService";
import {UserSettingService} from "@application/UserSetting/UserSettingService";
import {WebSocketService} from "@application/WebSocket/WebSocketService";

import {AdminRepository} from "@repositories/AdminRepository";
import LogRepository from "@repositories/LogRepository";

import {RelationService} from "@infraUtils/RelationService";

import {SftpClient} from "@infraServices/ThirdPartyClient/Sftp/SftpClient";

import {AuditLogger} from "@logger/AuditLogger";
import {Logger} from "@logger/Logger";

import Container from "./Container";

export const adminService = Container.resolve(AdminService);
export const adminUserService = Container.resolve(AdminUserService);
export const authService = Container.resolve(AuthService);
export const authUserService = Container.resolve(AuthUserService);
export const logService = Container.resolve(LogService);
export const fileService = Container.resolve(FileService);
export const formularyService = Container.resolve(FormularyService);
export const inventoryService = Container.resolve(InventoryService);
export const serviceDisruptionService = Container.resolve(ServiceDisruptionService);
export const serviceDisruptionPatientService = Container.resolve(ServiceDisruptionPatientService);
export const samlService = Container.resolve(SamlService);
export const facilityService = Container.resolve(FacilityService);
export const contactService = Container.resolve(ContactService);
export const facilityAdminService = Container.resolve(FacilityAdminService);
export const userSettingService = Container.resolve(UserSettingService);
export const historyPhysicalService = Container.resolve(HistoryPhysicalService);
export const divisionService = Container.resolve(DivisionService);
export const divisionSwornService = Container.resolve(DivisionSwornService);
export const patientService = Container.resolve(PatientService);
export const medicationListService = Container.resolve(MedicationListService);
export const facilityUnitsService = Container.resolve(FacilityUnitService);
export const bridgeTherapyService = Container.resolve(BridgeTherapyService);
export const roleService = Container.resolve(RoleService);
export const serviceListService = Container.resolve(ServiceListService);
export const roleServiceListService = Container.resolve(RoleServiceListService);
export const adminRoleService = Container.resolve(AdminRoleService);
export const refillStockService = Container.resolve(RefillStockService);
export const referenceGuideService = Container.resolve(ReferenceGuideService);
export const referenceGuideDrugService = Container.resolve(ReferenceGuideDrugService);
export const referenceGuideDrugProcessorService = Container.resolve(ReferenceGuideDrugProcessorService);
export const auditLogService = Container.resolve(AuditLogService);
export const relationService = Container.resolve(RelationService);
export const processService = Container.resolve(ProcessService);
export const processContactService = Container.resolve(ProcessContactService);
export const inventoryControlService = Container.resolve(InventoryControlService);
export const formularyLevelService = Container.resolve(FormularyLevelService);
export const cartService = Container.resolve(CartService);
export const reportService = Container.resolve(ReportService);
export const safeReportService = Container.resolve(SafeReportService);
export const safeReportEventLocationService = Container.resolve(SafeReportEventLocationService);
export const safeEventLocationService = Container.resolve(SafeEventLocationService);
export const safeAssignmentCommentService = Container.resolve(SafeAssignmentCommentService);
export const safeFacilityChecklistService = Container.resolve(SafeFacilityChecklistService);
export const facilityContactService = Container.resolve(FacilityContactService);
export const facilityChecklistService = Container.resolve(FacilityChecklistService);
export const safeReportNotificationService = Container.resolve(SafeReportNotificationService);
export const notificationService = Container.resolve(NotificationService);
export const notificationAdminService = Container.resolve(NotificationAdminService);
export const cartRequestFormService = Container.resolve(CartRequestFormService);
export const cartRequestLogService = Container.resolve(CartRequestLogService);
export const cartRequestDrugService = Container.resolve(CartRequestDrugService);
export const cartRequestDeductionService = Container.resolve(CartRequestDeductionService);
export const controlledDrugService = Container.resolve(ControlledDrugService);
export const centralSupplyLogService = Container.resolve(CentralSupplyLogService);
export const centralSupplyLogDrugService = Container.resolve(CentralSupplyLogDrugService);
export const perpetualInventoryService = Container.resolve(PerpetualInventoryService);
export const perpetualInventoryDeductionService = Container.resolve(PerpetualInventoryDeductionService);
export const webSocketService = Container.resolve(WebSocketService);
export const discrepancyLogService = Container.resolve(DiscrepancyLogService);
export const shiftCountLogService = Container.resolve(ShiftCountLogsService);
export const shiftCountService = Container.resolve(ShiftCountService);
export const shiftCountLogDrugService = Container.resolve(ShiftCountLogDrugsService);

export const inventoryHistoryService = Container.resolve(InventoryHistoryService);
export const serviceDependencyService = Container.resolve(ServiceDependencyService);
export const adminProcessorService = Container.resolve(AdminProcessorService);
export const formularyProcessorService = Container.resolve(FormularyProcessorService);
export const inventoryProcessorService = Container.resolve(InventoryProcessorService);
export const serviceDisruptionProcessorService = Container.resolve(ServiceDisruptionProcessorService);
export const facilityUnitProcessorService = Container.resolve(FacilityUnitProcessorService);
export const fileProcessorService = Container.resolve(FileProcessorService);
export const cartRequestDrugProcessorService = Container.resolve(CartRequestDrugProcessorService);
export const formularyLevelsProcessorService = Container.resolve(FormularyLevelsProcessorService);
export const inventoryHistoryProcessorService = Container.resolve(InventoryHistoryProcessorService);
export const cartInventoryService = Container.resolve(CartInventoryService);
export const cartInventoryLogsService = Container.resolve(CartInventoryLogsService);
export const cartInventoryLogsDrugService = Container.resolve(CartInventoryLogsDrugService);

export const adminRepository = container.resolve(AdminRepository);
export const logRepository = container.resolve(LogRepository);
export const auditLogger = container.resolve(AuditLogger);
export const logger = container.resolve(Logger);

export const emailUtils = Container.resolve(EmailUtils);
export const cloudStorageUtils = Container.resolve(CloudStorageUtils);
export const sftpClient = Container.resolve(SftpClient);
export const slackUtils = Container.resolve(SlackUtils);
